
platform :ios, ‘8.0’
target ‘Project-X’ do

pod 'Masonry', '~> 0.6.4'

pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"

pod 'AFNetworking', '~> 3.0.4'

pod 'MJExtension', '~> 3.0.10'

pod 'SDWebImage', '~> 3.7.5'

pod 'MBProgressHUD', '~> 0.9.2'

pod 'JPush', ‘3.0.5’

pod 'YYKit'

inhibit_all_warnings!
end
